### ISSUE TITLE
 ♻️ refactor 제 화면만 그런가 채팅창이 너무 작아용..

### ISSUE THREAD

**Issue by 4cozm** [4cozm/Multiplayer-Tower-Defense#69]
여러분도 그런가요? 좀만 더 키울까요?... 투명도 설정을 해서 배경이 더 잘보이게 한다면 좀 더 커져도 될거같은뎅
opacity를 0.3 정도로 주면 될거같아용

**Comment by mimihimesama** [comment]
제 화면에서도 조금 많이 작습니닷 좀 더 키워도 될 거 같아요
